language = "C"
include_guard = "MERUTABLE_H"
cpp_compat = true
documentation = true
tab_width = 4
style = "type"

[export]
include = [
    "MeruStatus",
    "MeruColumnType",
    "MeruBytesView",
    "MeruValueInner",
    "MeruValue",
    "MeruRow",
    "MeruColumnDef",
    "MeruSchema",
    "MeruOpenOptions",
    "MeruScanResult",
    "MeruMemtableStats",
    "MerucacheStats",
    "MeruStats",
    "MeruManifestInfo",
]

[export.rename]
"MerucacheStats" = "MeruCacheStats"

[parse]
parse_deps = false

[enum]
prefix_with_name = true

[fn]
prefix = "extern"
